version: '2'

services:

###
# Postgresql configuration
###
#
  postgres:
    image: postgres:9.5.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=mydemo
      - POSTGRES_PASSWORD=mydemo
      - POSTGRES_DB=mydemo

##

###
# Mongodb configuration
###
#
#  mongodb:
#    image: mongo
#
###

###
# Elasticsearch configuration
###
#
#  elasticsearch:
#    image: elasticsearch
#
###

